{% set name = "subsurface" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8496e54776d9e60f9bcb8a592dfac37cb245c6ad3662a70934ec8609eadf1314
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - xarray

test:
  imports:
    - subsurface

about:
  home: https://github.com/softwareunderground/subsurface
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: DataHub for geoscientific data in Python.
  description: |
    The DataHub for geoscientific data in Python has two main purposes:
    (1) Unify geometric data into data objects that all packages of the stack understand, and
    (2) Basic interactions with those data objects.
  doc_url: https://softwareunderground.github.io/subsurface/
  dev_url: https://github.com/softwareunderground/subsurface

extra:
  recipe-maintainers:
    - prisae
    - Leguark
